version: 2.1

executors:
  rust:
    resource_class: small
    docker:
      - image: cimg/rust:1.59-node



jobs:
  test-js:
    executor: rust
    steps:
      - checkout
      - restore_cache:
          keys:
            - pi-dashboard-{{checksum "yarn.lock"}}
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - save_cache:
          paths:
            - "node_modules/"
          key: pi-dashboard-{{checksum "yarn.lock"}}

workflows:
  version: 2
  build:
    jobs:
      - test-js
